# This file tells Netlify how to build Twelvety
# If you aren't using Netlify then you can delete this file

[build]
  command = "sed -i \"s|SECRET_WAP|${PROD_WAP}|g\" netlify.toml && npm run build"
  publish = "dist"

[[redirects]]
  from = "/whatsapp"
  to = "https://api.whatsapp.com/send?phone=SECRET_WAP"
  status = 200
  force = true